### ISSUE TITLE
What's the desired workflow for using posthog auth for open source python package?

### ISSUE THREAD

**Issue by AyushExel** [PostHog/posthog-python#102]
Hi there, I'm planning to use posthog + sentry for the product analytics at my company. I've previously using sentry + GA. The product is an open source python package so the code is available for the end user to see and modify. This is where I'm a little confused about the usage. 
With sentry and GA, you get a measurement id/dsn that you can use to send reports. Posthog requires authentication via api keys to send events. This would mean that I need to hardcode the key in the open source application? This doesn't seem safe. Or maybe posthog isn't really meant for this workflow? 
Apologies in advance if that's the case. Appreciate any help.

**Comment by neilkakkar** [comment]
Hey @AyushExel , PostHog's public write-only API key is meant for this use - it's equivalent to sentry's dsn. For example, you'll be able to find PostHog's API key in our codebase as well, and we package this for all self-hosted instances as well, so we get analytics from them.

As long as you're not using your personal API key (which can write+read everything) - you should be good to go.

**Comment by AyushExel** [comment]
Got it! thanks for the fast response

**Comment by AyushExel** [comment]
@neilkakkar I'm running into another issue while setting it up. 
I want to batch and rate limit my events so I'm using the post API as shown here https://posthog.com/docs/api/post-only-endpoints

For some reason I'm getting 400 with my public_api_key..
I deduced this to be the correct request format from the curl example. Am I missing something
```
url = 'https://app.posthog.com/capture/'
headers = {"Content-Type": "application/json"}
api_key='phc_oENDjGgHtmIDrV6puUiFem2RB4JA8gGWulfdulmMdZP'requests.post(self.url, json=data)

events = [{'event': event_name, 'metadata': self.metadata, 'properties': params, 'timestamp': datetime.datetime.now()}]
data = {
            "api_key": api_key,
            "distinct_id": CONFIG['uuid'], 
            "batch": events
            } 

res = requests.post(self.url, headers=self.headers, json=data)
```
