### ISSUE TITLE
Library does not properly handle feature flags with no % rollout

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog-python#24]
See sentry issue https://sentry.io/organizations/posthog/issues/2220836956/?project=1899813. If a feature flag is enabled for everyone without a % rollout, the client crashes. Notice that this is different from a 100% rollout which works fine.

```
unsupported operand type(s) for /: 'NoneType' and 'int'
```

posthoganalytics/client.py#L276
```python
response = _hash(key, distinct_id) <= (feature_flag['rollout_percentage'] / 100)
```

**Comment by timgl** [comment]
I think we should also fix this on the posthog side, to always return 100 if rollout_percentage is not set

**Comment by macobo** [comment]
I think this is a bug in the API which I may have introduced with the groups change.

Specifically, the api needs to return is_simple_flag True and rollout_percentage null for this.

I haven't been able to repro this - how did you set up the flag?
