### ISSUE TITLE
Library does not accept `uuid.UUID` as `distinct_id`, but Posthog uses UUIDs internally

### ISSUE THREAD

**Issue by andreipopovici** [PostHog/posthog-python#25]
This threw me for a loop for a second. I had to `str(myUUID)` to be able to use it as the `distinct_id` in all calls.

Since the documentation often shows UUIDs and doesn't explain that `distinct_id` should be a Number or `string_types`, it might be worth adding `uuid.UUID` to `ID_TYPES` at https://github.com/PostHog/posthog-python/blob/master/posthog/client.py#L24

Of course, one would need to cast the UUID to `str()` as well.

**Comment by Twixes** [comment]
Hey! Great suggestion, made PR #26, so this will land in the next library release..

**Comment by andreipopovici** [comment]
How'd I miss this little guy? https://github.com/PostHog/posthog-python/blob/9d620967f888d0000c7ede56bfba7a95a22b3065/posthog/client.py#L337

Bonus: the line number spells l33t!
