### ISSUE TITLE
Release new version of Python + update changelog for sentry

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog-python#34]
What was this project card about? @mariusandra
FYI I released `posthog-python` 1.4.0 on Tuesday, 18 May. That included the Sentry integration PR. Changelog: https://github.com/PostHog/posthog-python/blob/master/CHANGELOG.md#140---2021-05-07

**Comment by neilkakkar** [comment]
I think it was exactly this^ I was supposed to do this after those few PRs, but you beat me to it :D
