### ISSUE TITLE
Sentry integration not available in 1.4.0

### ISSUE THREAD

**Issue by tartieret** [PostHog/posthog-python#37]
Hello,

Sentry integration for posthog is available on master and in the release v1.4.0
However it seems that there is an issue with the package available on pypi, as it does not include the sentry folder.

Here is a snapshot showing that i installed posthog 1.4.0 in a python3.8 environment.

![image](https://user-images.githubusercontent.com/15146307/119922031-d9934500-bf23-11eb-86c3-c6de29f145a7.png)

Looking at the package installed in the virtual environment, it does not contain the `sentry` folder available on master:
![image](https://user-images.githubusercontent.com/15146307/119922164-1fe8a400-bf24-11eb-84b7-8052436438bb.png)

Could that be a packaging issue?

**Comment by neilkakkar** [comment]
Thanks, Thomas! That sounds about right, will fix!

**Comment by neilkakkar** [comment]
Thanks for letting us know about this, Thomas!

Have tested and resolved in v1.4.1 - please let me know if it still doesn't work for you.

**Comment by tartieret** [comment]
Thanks it's working !
