### ISSUE TITLE
$feature_flag_called event is not captured at the end of the Client.feature_enabled method call

### ISSUE THREAD

**Issue by utkuzih** [PostHog/posthog-python#58]
Posthog stopped tracking feature flag events from the Python library. I have a proposed fix in the following pull request: https://github.com/PostHog/posthog-python/pull/57

**Comment by utkuzih** [comment]
If anybody else runs into this issue, you can resolve it by not installing posthog 1.4.7 version of posthog.

`pip install posthog!=1.4.7`

**Comment by neilkakkar** [comment]
Thanks! Closed by https://github.com/PostHog/posthog-python/pull/57
