### ISSUE TITLE
Feature flag properties are not sent with capture calls

### ISSUE THREAD

**Issue by utkuzih** [PostHog/posthog-python#62]
In Javascript library, the `$feature/your-feature-name` is [sent with each capture event](https://posthog.com/docs/user-guides/feature-flags#querying-data-by-multivariate-feature-flag-values). In Python library, features are not sent as part of the capture events.

**Comment by utkuzih** [comment]
I don't believe there is a reliable way to set the `$feature/your-feature-name` from the Python library as there is no persistent state. I think having feature flag state within the event (instead of Persons) greatly limits the filtering capabilities of Insights reports. 

As a workaround, we will be sending `identify(properties={"$set_once":{"$feature/your-feature-name": "variant"}})` each time a feature flag is called. We will update our Insights reports to filter/breakdown by user properties instead of event properties. The only downside to above approach is that the `Experiments` page will not work as expected on PostHog.

**Comment by neilkakkar** [comment]
Hey @utkuzih, setting this information on Persons isn't a great idea, as with changing rollout % / changing selection on the feature flag means your insights get out of date, as the info on persons gets outdated.

This is why these properties are always on events.

What we'd want to do here is instead give a decent utility function that allows you to add `$feature/name` properties to your capture calls, while keeping the library stateless.

So, something like `get_feature_flag_properties_for_event(distinct_id)` that returns formatted values, which you can add to your capture events, as necessary.

**Comment by utkuzih** [comment]
@neilkakkar Not putting this field on Persons makes sense. 

I feel that the end-user should not care on whether feature flag properties are added on each `capture` call as its an implementation detail of PostHog. Alternatively, if we add the `get_feature_flag_properties_for_event` to each `capture` call, we may generate too many Decide API calls. 

I am definitely not so familiar with the overall architecture but this sounds like a case where a server-side solution may be more correct?

**Comment by neilkakkar** [comment]
Makes sense.

We don't want to put this on the server-side, since that slows down ingestion + easy to introduce consistency issues with the flags (value at time of code usage vs. value at time the event was finally ingested).

A middle ground I've been thinking of is to send these properties only when you care about them, instead of it being automatic - like in the frontend libraries.

So, for example, only when you call `posthog.get_feature_flag()`, and then use the value in some logic, does it make sense for events around here to send these feature flag properties. There's no extra decide calls involved, but it does mean that clients have to send feature flag values when they care about them.

Would this work for you?

**Comment by utkuzih** [comment]
What do you think of adding a `send_feature_flags=False` parameter to the `posthog.capture(...) ` call? 

This way we don't have to introduce another public API which looks similar to `posthog.feature_enabled(...)`. Also,  this would save us from returning `$feature/feture-name` and `$active_feature_flags` variables to the user.

**Comment by neilkakkar** [comment]
Sounds reasonable, actually.

We do need `get_feature_flag()` to support variants, but at the same time, only people conscious of speed/api calls can manually add the flags they need. I like it.

**Comment by utkuzih** [comment]
The #64 PR should add the `send_feature_flags=False` to the `posthog.capture(...)` calls. Also, I have exposed the `posthog.get_feature_variants(distinct_id, groups=None)` method in case somebody wants to see all enabled feature variants.

The `posthog.feature_enabled(...)` call already returns multivariate response as of #60 PR.
