### ISSUE TITLE
Posthog Django integration session_key is None

### ISSUE THREAD

**Issue by alper** [PostHog/posthog-python#7]
The example identifier listed for a Django app: `request.session.session_key` is None more often than not.

That is seemingly a known error and there's this workaround to it: 
https://stackoverflow.com/a/39188274/102315

Do I now need to check this everywhere in my code?

**Comment by Twixes** [comment]
Unfortunately that's just how Django works – there has to be a saved session. So if you want to use Django's session key, yep, you have to check for this.

**Comment by alper** [comment]
Is there an alternative?

**Comment by Twixes** [comment]
I don't know of any particular one, but there may be some packages for different handling of sessions. Checking may be the easier solution though.

**Comment by alper** [comment]
Fine.
