### ISSUE TITLE
Posthog's logging overrides custom logging

### ISSUE THREAD

**Issue by itaiperi** [PostHog/posthog-python#71]
I'm facing the following issue: My code has custom logging baked into it, with handlers and all. I installed posthog, imported it and want to start using it to capture events.
Problem is: Posthog's import happens before my own logging setup code (as in many cases, `import`s come before other code).
In the `client.py` file, [line 28](https://github.com/PostHog/posthog-python/blob/master/posthog/client.py#L28) sets up a default `basicConfig`, which sets up handlers of its own, which is an undesired behavior for me, as I don't want debug information going to `stderr`.
The least would be to set it up during the `Client` initialization, and not as part of the main file which executes on `import`, but I'm not even sure that might be enough, if people want to send events before they set up logging (not sure what could be the use-case, but it's possible I guess).

Example code:
```
import logging
import sys
import posthog

logger = logging.getLogger('')
handler = logging.StreamHandler(sys.stdout)
logger.addHandler(handler)
logger.setLevel(logging.DEBUG)
logger.debug('debug message')

Output:
debug message
debug message
debug message
```

And when I comment out the `import posthog` line, I get just:
```
Output:
debug message
```

**Comment by neilkakkar** [comment]
Makes sense, I'm changing this to only setup logging when the debug mode is set.
