### ISSUE TITLE
ResourceWarning on `posthog.capture()`

### ISSUE THREAD

**Issue by elongl** [PostHog/posthog-python#73]
I'm getting this unwanted warning coming from your library whenever I run `posthog.capture()`.

```py
sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('10.0.0.46', 56584), raddr=('34.202.126.243', 443)>
```

I've also attempted to silence it using the code below but it didn't work, it seems that `posthog` or one of its libraries override this.
```py
import warnings
warnings.filterwarnings(action="ignore", message="unclosed", category=ResourceWarning)
```

I've also muted the `posthog` logger which didn't have any affect.
```py
logging.getLogger('posthog').disabled = True
```

This is really important for me to fix as all my users are getting this error and it confuses them.

**Comment by neilkakkar** [comment]
Hey @elongl , do you have a reproducible test case?

We use `posthog-python` extensively as well, but haven't seen this before.

It sounds like warnings are disabled & only show up in dev mode: https://docs.python.org/3/library/devmode.html#devmode - are you doing something to switch these on?

**Comment by neilkakkar** [comment]
Saw the reproduction steps in the other lib.

If you create a new folder, setup venv, run `pip install posthoganalytics`, and create a script:

```
import posthoganalytics

posthoganalytics.capture()
```

and run it, do you still see the warning?
