### ISSUE TITLE
Add groups as kwarg to identify

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog-python#76]
We [already expose](https://github.com/PostHog/posthog-python/blob/master/posthog/client.py#L146-L174) `groups=` as a kwarg to `capture` but not to `identify` which is arguably the place you are most commonly wanting to use it.

This way instead of having to do
```python
posthoganalytics.identify(
  distinct_id, { "$groups": { "organization": 1234 } }
)
```
one could do the more clear:
```python
posthoganalytics.identify(distinct_id, groups={ "organization": 1234 })
```

**Comment by neilkakkar** [comment]
Identify is pretty much for identifying users, and users don't have groups (events do), so I think it's clearer not to do this.

https://github.com/PostHog/posthog/pull/12553/files#r1015421600
