### ISSUE TITLE
Backoff dependency range too narrow

### ISSUE THREAD

**Issue by steppi91** [PostHog/posthog-python#78]
## Issue description

In our setup we use segment and posthog-python (posthog through a dependency), and we ran into the error of not being able to use segment 2.2.1 and above because posthog-python requires backoff<2.0.0,>=1.10.0, while segment requires >=2.0.0

We overwrite backoff with a 2.0.x version, and posthog-python is still running as expected

Therefore relaxing the dependency condition and allowing backoff >=2.0.0 would be helpful

**Comment by bi01** [comment]
I also faced the same problem. why is package "backoff < 2.0.0". specified in dependencies when there is already "backoff == 2.2.1" ?

Please remove this restriction for the "posthog-python" package. Unless, of course, there are other reasons not to do it.

**Comment by EDsCODE** [comment]
Closed! https://github.com/PostHog/posthog-python/pull/85
